### ISSUE TITLE
Write usage documentation

### ISSUE THREAD

**Issue by arBmind** [hicknhack-software/ansible-libvirt#5]
This role set is quite verbose.
Please write some common usage examples.

**Comment by arBmind** [comment]
#1 might contain a good reference

**Comment by andrzejwp** [comment]
Unfortunately #1 is incomplete, the minimum to run it is

```
- role: domain/create
    libvirt_domain_name: "example"
    libvirt_ssh_port: 37331
    libvirt_domain_groups: ['example']
    libvirt_base_image: "{{ ansible_local.libvirt.facts.ubuntu_cloud_image_path }}"
```

after previously sucessfully applying the images/ubuntu-cloud role.

Complete working playbook:

```
- hosts: libvirt-server
  sudo: true

  roles:

  - role: images/ubuntu-cloud
    libvirt_images_ubuntu_cloud_image_url: "https://cloud-images.ubuntu.com/trusty/20160119/trusty-server-cloudimg-amd64-disk1.img"
  - role: domain/list
  - role: domain/create
    libvirt_domain_name: "example"
    libvirt_ssh_port: 37331
    libvirt_domain_groups: ['example']
    libvirt_base_image: "{{ ansible_local.libvirt.facts.ubuntu_cloud_image_path }}"

```

Also, please beware of the groups syntax issue, fixed in pr #6
